# Generated by Django 4.2.2 on 2023-06-27 13:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appreview', '0006_rename_title_review_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appreview',
            new_name='Ticket',
        ),
    ]
