# Generated by Django 4.2.2 on 2023-06-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appreview', '0007_rename_appreview_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
    ]
