# Generated by Django 4.2.2 on 2023-06-29 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appreview', '0008_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='date_created',
            new_name='created_on',
        ),
    ]
