# Generated by Django 4.2.2 on 2023-06-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appreview', '0011_alter_userfollows_followed_user_and_more'),
        ('authentication', '0003_alter_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='user_followers', to='appreview.userfollows'),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='user_following', to='appreview.userfollows'),
        ),
    ]
